### ISSUE TITLE
Set up and Verify Unity Collaboration with Git

### ISSUE THREAD

**Issue by DJ-CO** [annalieseschropp/checkers#26]
**Checklist:**
1. Each member: Ensure that you have Unity version 2020.3.18f1 installed. (https://unity3d.com/get-unity/download/archive)
2. Watch the git collaboration with Unity video.
3. As a group, decide on a collective gitignore to use, as well as rules for committing and merging.
4. Each member: push changes to the remote, and pull someone else's. Make note of any difficulties or problems encountered.
5. Revise the gitignore/commit process if necessary based on step 4

**Comment by annalieseschropp** [comment]
I was able to pull gittest and run the game without issue
