### ISSUE TITLE
11.5 Record Clear Control

### ISSUE THREAD

**Issue by DJ-CO** [annalieseschropp/checkers#69]
#### Persona and Action

*  As a user, I would like to clear the leaderboard records and game history records, so that I can make room for new records to track my progress.

#### Acceptance Criteria

* A button is  displayed that says 'DELETE RECORDS'
* On click, the table dedicated to storing the record data is cleared.

#### Time Estimate

* 2 hours

**Comment by annalieseschropp** [comment]
DestoryRecords()
